#!/usr/bin/env bash

# exit when a command fails
set -o errexit


TEXFILE=report3

rm -f *.aux *.log *.bbl *.blg *.lof *.lot *.out *.brf *.toc

pdflatex ${TEXFILE}
bibtex ${TEXFILE}
pdflatex ${TEXFILE}
pdflatex ${TEXFILE}

rm -f *.aux *.log *.bbl *.blg
